networks:
  webapi-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/24
services:
  webapi-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: webapi-sql
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
    env_file: "default.env"
    ports:
      - "14334:1433"
    networks:
      webapi-net:
        ipv4_address: 10.20.0.2
    volumes:
      - ./src/webapi-sql/data:/var/opt/mssql/data
      - ./src/webapi-sql/log:/var/opt/mssql/log
      - ./src/webapi-sql/secrets:/var/opt/mssql/secrets

  web:
    image: mywebapiapp
    container_name: webapi-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5052:5052"
    networks:
      webapi-net:
        ipv4_address: 10.20.0.3
    volumes:
      - .:/MyWebApiApp
      - app:/app
    depends_on:
      - webapi-sql
    
volumes:
  app:
